server:
  port: 8083
spring:
  rabbitmq:
        host: 192.168.96.129
        username: leyou
        password: 1234
        virtual-host: /leyou
  application:
    name: search-service
  jackson:
      default-property-inclusion: non_null
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.96.129:9300
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

