server:
  port: 8089
spring:
  rabbitmq:
    host: 192.168.96.129
    username: leyou
    password: 1234
    virtual-host: /leyou
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: ly.cart.exchange
    publisher-confirms: true
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
mybatis:
  type-aliases-package: com.leyou.order.pojo
ly:
  jwt:
    pubKeyPath: D:/heima/ssh/id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
      workerId: 1
      dataCenterId: 1